<?php

use Illuminate\Database\Seeder;

class AlbumsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $albums = array(
            array( // row #0
                'id' => 2,
                'name' => 'Cafe Sáng',
                'slug' => 'cafe-sang',
                'description' => 'Cafe Sáng',
                'view_count' => 0,
                'like_count' => 0,
                'share_count' => 0,
                'shot_at' => '2017-10-03',
                'cover' => 'album_covers/m8ZRLKimT9fBFCVGMNm1PJmzui79alWGPyOHMdpf.jpeg',
                'created_at' => '2017-10-26 03:47:05',
                'updated_at' => '2017-10-26 03:47:05',
                'status' => 'finished',
            ),
            array( // row #1
                'id' => 3,
                'name' => 'Cafe Sáng 2',
                'slug' => 'cafe-sang-2',
                'description' => 'Cafe Sáng',
                'view_count' => 0,
                'like_count' => 0,
                'share_count' => 0,
                'shot_at' => '2017-10-01',
                'cover' => 'album_covers/9V46keoOjcyTPDroINSEwju0DjnAiUcEq9dxAzJm.jpeg',
                'created_at' => '2017-10-26 03:47:36',
                'updated_at' => '2017-10-26 03:47:36',
                'status' => 'finished',
            ),
            array( // row #2
                'id' => 4,
                'name' => 'Ngày Lang Thang',
                'slug' => 'ngay-lang-thang',
                'description' => 'Ngày Lang Thang',
                'view_count' => 0,
                'like_count' => 0,
                'share_count' => 0,
                'shot_at' => '2017-10-07',
                'cover' => 'album_covers/EU709faYVZR7PVgpn04XTlcxmoXCgFM0cWgL952c.jpeg',
                'created_at' => '2017-10-26 03:48:25',
                'updated_at' => '2017-10-26 03:48:25',
                'status' => 'finished',
            ),
            array( // row #3
                'id' => 5,
                'name' => 'Gọi mưa',
                'slug' => 'goi-mua',
                'description' => 'Gọi mưa',
                'view_count' => 0,
                'like_count' => 0,
                'share_count' => 0,
                'shot_at' => '2017-10-08',
                'cover' => 'album_covers/9ybTIlZhvJyLi0peF4Hl68NDWWJdZ3rMvVmQ9eWv.jpeg',
                'created_at' => '2017-10-26 03:48:56',
                'updated_at' => '2017-10-26 03:48:56',
                'status' => 'finished',
            ),
            array( // row #4
                'id' => 6,
                'name' => 'Lắng',
                'slug' => 'lang',
                'description' => 'Lắng',
                'view_count' => 0,
                'like_count' => 0,
                'share_count' => 0,
                'shot_at' => '2017-10-10',
                'cover' => 'album_covers/cSAKhbbJKEivhN5qooyz2hI6Yi69bnq71UXT4Moo.jpeg',
                'created_at' => '2017-10-26 03:49:28',
                'updated_at' => '2017-10-26 03:49:28',
                'status' => 'finished',
            ),
            array( // row #5
                'id' => 7,
                'name' => 'Bèo dạt mây trôi',
                'slug' => 'beo-dat-may-troi',
                'description' => 'Bèo dạt mây trôi',
                'view_count' => 0,
                'like_count' => 0,
                'share_count' => 0,
                'shot_at' => '2017-10-12',
                'cover' => 'album_covers/MHGXwg8P4hK78VjcowOmjZD1ZvMYnKEHpQ1OXlUp.jpeg',
                'created_at' => '2017-10-26 03:49:59',
                'updated_at' => '2017-10-26 03:49:59',
                'status' => 'finished',
            ),
            array( // row #6
                'id' => 8,
                'name' => 'Where are you know?',
                'slug' => 'where-are-you-know',
                'description' => 'Em giờ nơi đâu',
                'view_count' => 0,
                'like_count' => 0,
                'share_count' => 0,
                'shot_at' => '2017-10-18',
                'cover' => 'album_covers/hcLFnpZZJpxlWZVO7sMQKMSsUqyP5ao8jBOhr11p.jpeg',
                'created_at' => '2017-10-26 03:50:36',
                'updated_at' => '2017-10-26 03:50:36',
                'status' => 'finished',
            ),
            array( // row #7
                'id' => 9,
                'name' => 'Tâm sự với người lạ',
                'slug' => 'tam-su-voi-nguoi-la',
                'description' => 'Đôi khi anh muốn tâm sự cùng người lạ',
                'view_count' => 0,
                'like_count' => 0,
                'share_count' => 0,
                'shot_at' => '2017-10-17',
                'cover' => 'album_covers/ri8rcRwTIJkccJO5ZhPsqsT5ejcoMH4tZGdC78uS.jpeg',
                'created_at' => '2017-10-26 03:51:56',
                'updated_at' => '2017-10-26 03:51:56',
                'status' => 'finished',
            ),
            array( // row #8
                'id' => 10,
                'name' => 'Sâu trong em',
                'slug' => 'sau-trong-em',
                'description' => 'Là ai',
                'view_count' => 0,
                'like_count' => 0,
                'share_count' => 0,
                'shot_at' => '2017-10-20',
                'cover' => 'album_covers/bTBHPC1ncRBXbIY1OHdbtJq1E40ZUQSOv1RfWZU3.jpeg',
                'created_at' => '2017-10-26 03:52:27',
                'updated_at' => '2017-10-26 03:52:27',
                'status' => 'finished',
            ),
            array( // row #9
                'id' => 11,
                'name' => 'Chết dần',
                'slug' => 'chet-dan',
                'description' => 'Chết mòn',
                'view_count' => 0,
                'like_count' => 0,
                'share_count' => 0,
                'shot_at' => '2017-10-07',
                'cover' => 'album_covers/Avp9EVo5kmozpefM7VD6iBtMq70vbsWJkIwPrxr5.jpeg',
                'created_at' => '2017-10-26 03:52:50',
                'updated_at' => '2017-10-26 03:52:50',
                'status' => 'finished',
            ),
            array( // row #10
                'id' => 12,
                'name' => 'Cuốn theo chiều gió',
                'slug' => 'cuon-theo-chieu-gio',
                'description' => 'lá',
                'view_count' => 0,
                'like_count' => 0,
                'share_count' => 0,
                'shot_at' => '2017-10-24',
                'cover' => 'album_covers/hnqIMmMYnjU3hD2ABrcEwdEtn3W1IBPp74tSJK1M.jpeg',
                'created_at' => '2017-10-26 03:53:22',
                'updated_at' => '2017-10-26 03:53:22',
                'status' => 'finished',
            ),
            array( // row #11
                'id' => 13,
                'name' => 'Silver',
                'slug' => 'silver',
                'description' => 'Silver',
                'view_count' => 0,
                'like_count' => 0,
                'share_count' => 0,
                'shot_at' => '2017-10-22',
                'cover' => 'album_covers/Xzy7h8KBLNNg3iox4yg9xZ1NO4o4idZPViRDI62c.jpeg',
                'created_at' => '2017-10-26 03:54:14',
                'updated_at' => '2017-10-26 03:54:14',
                'status' => 'finished',
            ),
            array( // row #12
                'id' => 14,
                'name' => 'Một chút gió một chút mắt cay cay',
                'slug' => 'mot-chut-gio-mot-chut-mat-cay-cay',
                'description' => 'Ha',
                'view_count' => 0,
                'like_count' => 0,
                'share_count' => 0,
                'shot_at' => '2017-10-17',
                'cover' => 'album_covers/5F3elsmwClNmfVjLEcCFLv6K21SVCqHSem8ablLN.jpeg',
                'created_at' => '2017-10-26 03:54:40',
                'updated_at' => '2017-10-26 03:54:40',
                'status' => 'finished',
            ),
        );
        
        DB::table('albums')->insert($albums);
    }
}
